apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootloader.yaml
  - pod-sweeper.yaml
  - admin-service-account.yaml
  - server.yaml
  - temporal.yaml
  - volume-configs.yaml
  - webapp.yaml
  - worker.yaml
